[package]
name = "fuzzy_match"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
fuse-rust = { version = "0.4.0", default-features = false}
uuid = { version = "1", features = ["v4", "js"] }
web-sys = { version = "0.3", features = ["console"] }
